# Generated by Django 5.2.4 on 2025-07-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomers',
            new_name='Customers',
        ),
    ]
