# Generated by Django 5.2.4 on 2025-07-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_cutomers_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
