# Generated by Django 5.2.4 on 2025-07-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_birth_day_customers_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='order',
        ),
    ]
