# Generated by Django 5.2.4 on 2025-07-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0002_tagitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagitem',
            name='content_type',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagitem',
            name='object_id',
            field=models.PositiveBigIntegerField(default='-'),
            preserve_default=False,
        ),
    ]
